package net.tecgurus.entities;
// Generated 09-sep-2016 18:21:54 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name = "cuenta", catalog = "tec_gurus")
public class Cuenta implements java.io.Serializable {

	private int idCta;
	private String noCta;
	private int idTipCta;
	private Date fchAlt;
	private long idEst;
	private Date fchCre;
	private Date fchMod;
	private String noTar;
	private BigDecimal blncCta;

	public Cuenta() {
	}

	public Cuenta(int idCta, int idTipCta, Date fchAlt, long idEst, Date fchCre) {
		this.idCta = idCta;
		this.idTipCta = idTipCta;
		this.fchAlt = fchAlt;
		this.idEst = idEst;
		this.fchCre = fchCre;
	}

	public Cuenta(int idCta, String noCta, int idTipCta, Date fchAlt, long idEst, Date fchCre, Date fchMod,
			String noTar, BigDecimal blncCta) {
		this.idCta = idCta;
		this.noCta = noCta;
		this.idTipCta = idTipCta;
		this.fchAlt = fchAlt;
		this.idEst = idEst;
		this.fchCre = fchCre;
		this.fchMod = fchMod;
		this.noTar = noTar;
		this.blncCta = blncCta;
	}

	@Id

	@Column(name = "id_cta", unique = true, nullable = false)
	public int getIdCta() {
		return this.idCta;
	}

	public void setIdCta(int idCta) {
		this.idCta = idCta;
	}

	@Column(name = "no_cta", length = 20)
	public String getNoCta() {
		return this.noCta;
	}

	public void setNoCta(String noCta) {
		this.noCta = noCta;
	}

	@Column(name = "id_tip_cta", nullable = false)
	public int getIdTipCta() {
		return this.idTipCta;
	}

	public void setIdTipCta(int idTipCta) {
		this.idTipCta = idTipCta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fch_alt", nullable = false, length = 19)
	public Date getFchAlt() {
		return this.fchAlt;
	}

	public void setFchAlt(Date fchAlt) {
		this.fchAlt = fchAlt;
	}

	@Column(name = "id_est", nullable = false)
	public long getIdEst() {
		return this.idEst;
	}

	public void setIdEst(long idEst) {
		this.idEst = idEst;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fch_cre", nullable = false, length = 19)
	public Date getFchCre() {
		return this.fchCre;
	}

	public void setFchCre(Date fchCre) {
		this.fchCre = fchCre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fch_mod", length = 19)
	public Date getFchMod() {
		return this.fchMod;
	}

	public void setFchMod(Date fchMod) {
		this.fchMod = fchMod;
	}

	@Column(name = "no_tar", length = 20)
	public String getNoTar() {
		return this.noTar;
	}

	public void setNoTar(String noTar) {
		this.noTar = noTar;
	}

	@Column(name = "blnc_cta", precision = 20)
	public BigDecimal getBlncCta() {
		return this.blncCta;
	}

	public void setBlncCta(BigDecimal blncCta) {
		this.blncCta = blncCta;
	}

}
