
package net.tecgurus.bancoservice._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BancoServicePortType", targetNamespace = "http://www.tecgurus.net/bancoService/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BancoServicePortType {


    /**
     * 
     * @param bancoDataRequest
     * @return
     *     returns net.tecgurus.bancoservice._1.BancoDataResponse
     */
    @WebMethod(action = "http://www.tecgurus.net/bancoService/getDataOperation")
    @WebResult(name = "BancoDataResponse", targetNamespace = "http://www.tecgurus.net/bancoService/1.0", partName = "BancoDataResponse")
    public BancoDataResponse getDataOperation(
        @WebParam(name = "BancoDataRequest", targetNamespace = "http://www.tecgurus.net/bancoService/1.0", partName = "BancoDataRequest")
        BancoDataRequest bancoDataRequest);

    /**
     * 
     * @param clienteDataRequest
     * @return
     *     returns net.tecgurus.bancoservice._1.ClienteDataResponse
     */
    @WebMethod(action = "http://www.tecgurus.net/bancoService/getClientesOperation")
    @WebResult(name = "ClienteDataResponse", targetNamespace = "http://www.tecgurus.net/bancoService/1.0", partName = "ClienteDataRespone")
    public ClienteDataResponse getClientesOperation(
        @WebParam(name = "ClienteDataRequest", targetNamespace = "http://www.tecgurus.net/bancoService/1.0", partName = "ClienteDataRequest")
        ClienteDataRequest clienteDataRequest);

}
