
package net.tecgurus.bancoservice._1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BancoService", targetNamespace = "http://www.tecgurus.net/bancoService/1.0", wsdlLocation = "file:/C:/Users/Amaro/Documents/TEC_GURUS_GIT/tg-frameworks/tg-frameworks/clase7/inicial/sfsobaweb/src/main/webapp/wsdl/bancoService.wsdl")
public class BancoService
    extends Service
{

    private final static URL BANCOSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANCOSERVICE_EXCEPTION;
    private final static QName BANCOSERVICE_QNAME = new QName("http://www.tecgurus.net/bancoService/1.0", "BancoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Amaro/Documents/TEC_GURUS_GIT/tg-frameworks/tg-frameworks/clase7/inicial/sfsobaweb/src/main/webapp/wsdl/bancoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANCOSERVICE_WSDL_LOCATION = url;
        BANCOSERVICE_EXCEPTION = e;
    }

    public BancoService() {
        super(__getWsdlLocation(), BANCOSERVICE_QNAME);
    }

    public BancoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANCOSERVICE_QNAME, features);
    }

    public BancoService(URL wsdlLocation) {
        super(wsdlLocation, BANCOSERVICE_QNAME);
    }

    public BancoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANCOSERVICE_QNAME, features);
    }

    public BancoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BancoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BancoServicePortType
     */
    @WebEndpoint(name = "BancoServicePort")
    public BancoServicePortType getBancoServicePort() {
        return super.getPort(new QName("http://www.tecgurus.net/bancoService/1.0", "BancoServicePort"), BancoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BancoServicePortType
     */
    @WebEndpoint(name = "BancoServicePort")
    public BancoServicePortType getBancoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tecgurus.net/bancoService/1.0", "BancoServicePort"), BancoServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANCOSERVICE_EXCEPTION!= null) {
            throw BANCOSERVICE_EXCEPTION;
        }
        return BANCOSERVICE_WSDL_LOCATION;
    }

}
